CREATE OR REPLACE NONEDITIONABLE PROCEDURE PROCEDURE1 
(
  PARAM1 IN VARCHAR2 
) AS 
BEGIN
  
  DECLARE PARAM2 VARCHAR2(30);
  BEGIN
--  SET PARAM2:= '3';
    DBMS_OUTPUT.PUT(', ');
  END;
END PROCEDURE1;
